name = "mock-config"

[fenrir_config]
n_self_play_nodes = 1
n_train_nodes = 1
n_model_replica_self_play = 1
n_model_replica_train = 1
use_mpi = false
mini_batch_size = 4
n_training_step_per_cycle = 10
n_self_play_games = 20
n_games_per_tournament = 10
model_update_threshold = 0.55
concurrent_training = false
replay_buffer_capacity = 100
run_time_hr = 1
momentum = 0.01
learning_rate_schedule = "AlphaGoZero"
weight_decay = 0.001

[mcts_config]
c_puct = 0.3
n_sim = 50
dirichlet_alpha = 0.03
dirichlet_epsilon = 0.25
temp_schedule_target_policy = "AlphaGoZero"
temp_schedule_move_selection = "AlphaGoZero"

[model_sync_config]

[model_sync_config.grad]
type = "Ave"

[setup_config]
use_mpi = false

[[setup_config.module_load_infos]]
path = "foo"
    [setup_config.module_load_infos.device]
    type = "Cpu"
    
    [setup_config.module_load_infos.config]
    policy_out_features = 12
    board_size = 7
    value_hidden_layer_unit_count = 32
    num_convblocks = 2
    in_features = 5
    conv_filters = 3
    kernel_size = 3

