[package]
name = "bitboard"
version = "0.1.0"
edition = "2024"

[dependencies]
rawbytes = "1.0.1"
bitflags = "2.9.1"
rand = {workspace = true}
bincode = "2"

[lib]
crate-type = ["rlib"]
bench = false
